- name: Copying mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb-org
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: mongod enabling and starting
  ansible.builtin.service:
    name: mongod
    enabled: yes
    state: started

- name: Allowing remote access
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting mongod service
  ansible.builtin.service:
    name: mongod
    state: restarted