- name: install mysql
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: check cites schema exists or not
    ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: print output
    ansible.builtin.debug:
      msg: "Cites schema is {{schema}}"

  - name: loading schema
    ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -pRoboShop@1 < /app/schema/shipping.sql
    when: schema.stdout != "1"